version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: ngockhuong
      POSTGRES_PASSWORD: ngockhuong
      TZ: "Asia/Ho_Chi_Minh"
    ports:
      - "55432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
